<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="8" passed="5" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-05-13T12:02:15 IST" name="AllVehicleTests" finished-at="2025-05-13T12:02:22 IST" duration-ms="6992">
    <groups>
    </groups>
    <test started-at="2025-05-13T12:02:15 IST" name="VehicleTests" finished-at="2025-05-13T12:02:22 IST" duration-ms="6992">
      <class name="tests.VehicleSoldTest">
        <test-method signature="testVehicleSold()[pri:0, instance:tests.VehicleSoldTest@52e6fdee]" started-at="2025-05-13T12:02:21 IST" name="testVehicleSold" finished-at="2025-05-13T12:02:21 IST" duration-ms="303" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testVehicleSold -->
      </class> <!-- tests.VehicleSoldTest -->
      <class name="tests.CurrentMonth">
        <test-method signature="testCurrentMonth()[pri:0, instance:tests.CurrentMonth@6c80d78a]" started-at="2025-05-13T12:02:21 IST" name="testCurrentMonth" finished-at="2025-05-13T12:02:22 IST" duration-ms="335" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCurrentMonth -->
      </class> <!-- tests.CurrentMonth -->
      <class name="tests.LastMonth">
        <test-method signature="testLastMonth()[pri:0, instance:tests.LastMonth@62150f9e]" started-at="2025-05-13T12:02:22 IST" name="testLastMonth" finished-at="2025-05-13T12:02:22 IST" duration-ms="383" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLastMonth -->
      </class> <!-- tests.LastMonth -->
      <class name="tests.VehiclesInvoicedButNotDeliveredTest">
        <test-method signature="testVehiclesInvoicedButNotDelivered()[pri:0, instance:tests.VehiclesInvoicedButNotDeliveredTest@14dd9eb7]" started-at="2025-05-13T12:02:21 IST" name="testVehiclesInvoicedButNotDelivered" finished-at="2025-05-13T12:02:21 IST" duration-ms="326" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[vehiclesInvoicedButNotDelivered expected [2] but found [69]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: vehiclesInvoicedButNotDelivered expected [2] but found [69]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at tests.VehiclesInvoicedButNotDeliveredTest.testVehiclesInvoicedButNotDelivered(VehiclesInvoicedButNotDeliveredTest.java:19)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testVehiclesInvoicedButNotDelivered -->
      </class> <!-- tests.VehiclesInvoicedButNotDeliveredTest -->
      <class name="tests.VehiclesInvoicedThisMonthTest">
        <test-method signature="testVehiclesInvoicedThisMonth()[pri:0, instance:tests.VehiclesInvoicedThisMonthTest@42e99e4a]" started-at="2025-05-13T12:02:20 IST" name="testVehiclesInvoicedThisMonth" finished-at="2025-05-13T12:02:21 IST" duration-ms="262" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testVehiclesInvoicedThisMonth -->
      </class> <!-- tests.VehiclesInvoicedThisMonthTest -->
      <class name="tests.VehiclesBookedYesterdayTest">
        <test-method signature="testVehiclesBookedYesterday()[pri:0, instance:tests.VehiclesBookedYesterdayTest@1d9b7cce]" started-at="2025-05-13T12:02:20 IST" name="testVehiclesBookedYesterday" finished-at="2025-05-13T12:02:20 IST" duration-ms="300" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[vehiclesBookedYesterday expected [2] but found [0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: vehiclesBookedYesterday expected [2] but found [0]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at tests.VehiclesBookedYesterdayTest.testVehiclesBookedYesterday(VehiclesBookedYesterdayTest.java:19)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testVehiclesBookedYesterday -->
      </class> <!-- tests.VehiclesBookedYesterdayTest -->
      <class name="tests.VehiclesInvoicedYesterdayTest">
        <test-method signature="testVehiclesInvoicedYesterday()[pri:0, instance:tests.VehiclesInvoicedYesterdayTest@4d9e68d0]" started-at="2025-05-13T12:02:20 IST" name="testVehiclesInvoicedYesterday" finished-at="2025-05-13T12:02:20 IST" duration-ms="315" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[vehiclesInvoicedYesterday expected [2] but found [0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: vehiclesInvoicedYesterday expected [2] but found [0]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at tests.VehiclesInvoicedYesterdayTest.testVehiclesInvoicedYesterday(VehiclesInvoicedYesterdayTest.java:19)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testVehiclesInvoicedYesterday -->
      </class> <!-- tests.VehiclesInvoicedYesterdayTest -->
      <class name="tests.VehicleSalesTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:tests.VehicleSalesTest@795cd85e]" started-at="2025-05-13T12:01:53 IST" name="setUp" finished-at="2025-05-13T12:02:15 IST" duration-ms="22016" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testVehicleSales()[pri:0, instance:tests.VehicleSalesTest@795cd85e]" started-at="2025-05-13T12:02:15 IST" name="testVehicleSales" finished-at="2025-05-13T12:02:20 IST" duration-ms="4713" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testVehicleSales -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:tests.VehicleSalesTest@795cd85e]" started-at="2025-05-13T12:02:22 IST" name="tearDown" finished-at="2025-05-13T12:02:23 IST" duration-ms="479" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- tests.VehicleSalesTest -->
    </test> <!-- VehicleTests -->
  </suite> <!-- AllVehicleTests -->
</testng-results>
